<a href="https://colab.research.google.com/github/hhsharma5/notebookTrials/blob/main/FirstTrial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
x = 5
print(x)

5


In [ ]:
# Importing array for array creations

import array

# Creating an array as integer type
a = array.array('i', [1, 2, 3])

print(a)

Some text here, its pretty cool

```
This is formatted as code
```



In [13]:
# Using numpy to create arrays

import numpy as np

arr1 = np.array([2, 5, 6])
print(arr1)
print(type(arr1))
print(arr1.size)
print(arr1.ndim)
print(arr1.dtype)

'''
Suppose you want to optimize the space and know the range beforehand
you can set the bits with dtype
''' 
arr2 = np.array([2, 3, 4], dtype="int8")
print(arr2.dtype)

# create 2 d arrays
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print(arr3.ndim)

# create 3 d array
arr4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr4)
print(arr4.ndim)

[2 5 6]
<class 'numpy.ndarray'>
3
1
int64
int8
[[1 2 3]
 [4 5 6]]
2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [22]:
# first and last element of the array

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d[0], arr2d[-1])

# slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[::2])

# 2d array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 1:])

# print by rows
print(arr[0:2, 2])


[1 2 3] [4 5 6]
[1 3 5]
[5 6]
[3 6]
