<a href="https://colab.research.google.com/github/hhsharma5/notebookTrials/blob/main/numpy_extra_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
'''
Numpy array copy as view

The main difference between a copy and a view of an array is that
a copy is a new array and a view is just a view of the original array
'''

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 42

print(arr)
print(x)

# view will affect the original array
y = arr.view()
y[0] = 43
print(arr)
print(y)

[1 2 3 4 5]
[42  2  3  4  5]
[43  2  3  4  5]
[43  2  3  4  5]


In [4]:
# shape
arr = np.array([[1, 2, 3], [5, 6, 7]])
print(arr.shape)

(2, 3)


In [6]:
# reshape
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = arr.reshape(2, 3)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
