<a href="https://colab.research.google.com/github/hhsharma5/notebookTrials/blob/main/numpy_extra_examples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
'''
Numpy array copy as view

The main difference between a copy and a view of an array is that
a copy is a new array and a view is just a view of the original array
'''

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 42

print(arr)
print(x)

# view will affect the original array
y = arr.view()
y[0] = 43
print(arr)
print(y)

[1 2 3 4 5]
[42  2  3  4  5]
[43  2  3  4  5]
[43  2  3  4  5]


In [4]:
# shape
arr = np.array([[1, 2, 3], [5, 6, 7]])
print(arr.shape)

(2, 3)


In [6]:
# reshape
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = arr.reshape(2, 3)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
# iterating with numpy

# simple iteration 
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7,8]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

print("=======")

# numpy nd iterator
for x in np.nditer(arr):
  print(x)

print("======")
for id, x in np.ndenumerate(arr):
  print(id, x)

In [15]:
# Joining arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
print(arr3)

# join 2d arrays by rows

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate((arr1, arr2)))

# default axis is 0
# join by columns 
print(np.concatenate((arr1, arr2), axis=1))

[1 2 3 4 5 6]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [18]:
# Filtering

arr = np.array([41, 42, 43, 44])
evenFilter = [False, True, False, True]

newArr = arr[evenFilter]
print(newArr)

# shortcut of creating a fiter
newEvenFilter = (arr % 2) == 0
newFinalArr = arr[newEvenFilter]
print(newFinalArr)

# addition
print(arr + 10)

[42 44]
[42 44]
[51 52 53 54]
